### ISSUE TITLE
依赖

### ISSUE THREAD

**Issue by gjhkael** [xmpy/hvpi#1]
<dependency>
          <groupId>xuggle</groupId>
          <artifactId>xuggle-xuggler</artifactId>
          <version>5.4</version>
     </dependency>
      <dependency> 
           <groupId>xuggle</groupId> 
           <artifactId>xuggle-utils</artifactId> 
           <version>1.22</version> 
      </dependency>
这两个依赖下载不下来，请问有什么解决方法吗？我使用VPN也没用。

**Comment by xmpy** [comment]
I have fixed this bug by moving xuggle jars to lib directory. This bug may be due to Xuggle project has been deprecated for a long time. Hope you can help us figure out better way than Xuggle to parse videos.
